variables:
  - name: Build.Repository.Clean
    value: true
  - name: _HelixType
    value: build/product
  - name: _HelixSource
    value: pr/dotnet/arcade-minimalci-sample/$(Build.SourceBranch)
  - name: _HelixTestType
    value: test/product/
  - name: _XUnitProject
    value: $(Build.SourcesDirectory)/Hello.Tests/Hello.Tests.csproj
  - name: _XUnitTargetFramework
    value: netcoreapp2.0
  - name: _XUnitRunnerVersion
    value: 2.4.1
  - name: _DotNetCliPackageType
    value: sdk
  - name: _DotNetCliVersion
    value: 2.1.403
  - name: _HelixAccessToken
    value: ''

resources:
  containers:
  - container: LinuxContainer
    image: microsoft/dotnet-buildtools-prereqs:ubuntu-14.04-cross-0cd4667-20170319080304

# CI and PR triggers
trigger:
- master

pr:
- master

jobs:
- template: /eng/common/templates/job/job.yml
  parameters:
    name: Linux
    enableTelemetry: true
    enablePublishBuildArtifacts: true
    helixRepo: dotnet/arcade-minimalci-sample
    pool:
      name: Hosted Ubuntu 1604
    container: LinuxContainer
    strategy:
      matrix:
        debug_configuration:
          _BuildConfig: Debug
        release_configuration:
          _BuildConfig: Release
    steps:
    - script: eng/common/msbuild.sh --ci ./publish.proj
      name: Build
      displayName: Build
      condition: succeeded()
    - task: PublishBuildArtifacts@1
      displayName: Publish Logs to VSTS
      inputs:
        PathtoPublish: '$(Build.SourcesDirectory)/artifacts/log/$(_BuildConfig)'
        PublishLocation: Container
        ArtifactName: $(Agent.Os)_$(Agent.JobName)
      continueOnError: true
      condition: always()
    variables:
      _HelixBuildConfig: $(_BuildConfig)
